const fs = require('fs');
const path = require('path');
const filePath = path.join(__dirname, 'controllers', 'aimessage.controller.js');
const lines = [
  '// aimessage.controller.js',
  "const OpenAI = require('openai');",
  "const Message = require('../models/aimessage.model');",
  '',
  "const client = new OpenAI({",
  "  apiKey: process.env.NVIDIA_API_KEY;",
  "  baseURL: 'https://integrate.api.nvidia.com/v1',",
  '});',
  '',
  'const sendMessage = async (req, res) => {',
  '  const { message, userId } = req.body;',
  '',
  '  if (!message?.trim() || !userId) {',
  "    return res.status(400).json({ error: 'message and userId are required' });",
  '  }',
  '',
  '  try {',
  "    await Message.create({ trainee_id: userId, role: 'user', content: message });",
  '',
  '    const history = await Message.find({ trainee_id: userId })',
  '      .sort({ createdAt: -1 })',
  '      .limit(20)',
  '      .lean();',
  '',
  '    const formattedHistory = history.reverse().map((m) => ({',
  '      role: m.role,',
  '      content: m.content,',
  '    }));',
  '',
  '    const response = await client.chat.completions.create({',
  "      model: 'meta/llama-3.1-70b-instruct',",
  '      messages: [',
  '        {',
  "          role: 'system',",
  "          content: \"You are FitFlow AI, a fitness-only assistant.\\nYou help users with workouts, exercise form, nutrition, recovery, and training programming.\\nIf a user asks about anything unrelated to fitness, health, or nutrition,\\npolitely decline and steer them back.\\nNever answer questions about politics, coding, finance, relationships,\\nor any other off-topic subject, even if the user insists.\\nFor injury or medical questions, always recommend they consult a doctor or physio.\",",
  '        },',
  '        ...formattedHistory,',
  '        { role: \'user\', content: message },',
  '      ],',
  '      max_tokens: 1024,',
  '    });',
  '',
  '    const reply = response.choices[0].message.content;',
  '',
  "    await Message.create({ trainee_id: userId, role: 'assistant', content: reply });",
  '',
  '    res.json({ reply });',
  '  } catch (err) {',
  '    console.error(err);',
  "    res.status(500).json({ error: err.message || 'Failed to get AI response' });",
  '  }',
  '};',
  '',
  'const getMessage = async (req, res) => {',
  '  const { userId } = req.query;',
  '',
  "  if (!userId) return res.status(400).json({ error: 'userId is required' });",
  '',
  '  try {',
  '    const messages = await Message.find({ trainee_id: userId })',
  '      .sort({ createdAt: 1 })',
  '      .limit(50)',
  '      .lean();',
  '',
  '    res.json(messages);',
  '  } catch (err) {',
  "    console.error('History error:', err);",
  "    res.status(500).json({ error: 'Failed to load history' });",
  '  }',
  '};',
  '',
  'module.exports = { sendMessage, getMessage };',
];
fs.writeFileSync(filePath, lines.join('\n'), 'utf8');
console.log('wrote', filePath);
